import { readFile, readdir, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const files = ['index.html','encode.html','manifest.webmanifest'];
async function walk(dir) {
  for (const entry of await readdir(dir,{withFileTypes:true})) {
    const path=`${dir}/${entry.name}`;
    if(entry.isDirectory()) await walk(path); else files.push(path);
  }
}
for(const dir of ['js','css','icons','asset/fonts','LICENSES']) await walk(dir);
files.sort();
const hash=createHash('sha256');
for(const file of files) {
  const data=await readFile(file);
  hash.update(file).update(/\.(png|woff2)$/.test(file) ? data : data.toString('utf8').replace(/\r\n/g,'\n'));
}
hash.update((await readFile('sw.js','utf8')).replace(/\r\n/g,'\n'));
const output=`// Generated by npm run prepare:offline; commit with application changes.\nself.OFFLINE_VERSION = '${hash.digest('hex').slice(0,16)}';\nself.OFFLINE_ASSETS = ${JSON.stringify(files,null,2)};\n`;
if(process.argv.includes('--check')) {
  if((await readFile('sw-assets.js','utf8')).replace(/\r\n/g,'\n')!==output) throw new Error('Offline resource index is stale; run npm run prepare:offline');
} else await writeFile('sw-assets.js',output);
